pygments: false
title: angularjs.info
url: http://angularjs-info.github.io
description: AngularJS examples, recipes & tutorials
paginate: 5
paginate_files: index.html
permalink: /:year/:month/:title
markdown: kramdown