title: ng-learn.org  - Learn AngularJS @ng_learn
url: http://ng-learn.org
description: AngularJS examples, recipes & tutorials including directives, binding, filters, ngRepeat, testing, isolate scopes
paginate: 5
paginate_files: index.html
permalink: /:year/:month/:title/
highlighter: true
email: info@ng-learn.org
keywords: angularjs, ng-conf
author: Santiago Esteva, Gonzalo Do Carmo Norte, Mariano Wahlmann
copyright: 2014 © All Rights Reserved ng-learn.org
image: http://ng-learn.org/img/logo.svg
exclude: ["vendor"]
plugins: [jekyll-paginate]
